sonar.projectName=openimis-be_py
sonar.projectKey=HABTec_openimis-be_py
sonar.organization=habtec

sonar.sources=openIMIS
sonar.sourceEncoding=UTF-8
sonar.exclusions= "**/migrations/**,**/static/**,**/media/**,**/tests/**"
